import type { TableDesignerDriver, TableDesignerTypeOption } from "../types";
import { buildApplySqlOracle } from "../applySql";
import {
  createEmptyField,
  createEmptyIndex,
  createGenericDriver,
  fromSchemaGeneric,
  validateGeneric,
} from "./genericDriver";

const ORACLE_TYPES: TableDesignerTypeOption[] = [
  { value: "VARCHAR2", label: "VARCHAR2" },
  { value: "NUMBER", label: "NUMBER" },
  { value: "INTEGER", label: "INTEGER" },
  { value: "DATE", label: "DATE" },
  { value: "TIMESTAMP", label: "TIMESTAMP" },
  { value: "CLOB", label: "CLOB" },
  { value: "BLOB", label: "BLOB" },
  { value: "CHAR", label: "CHAR" },
  { value: "NVARCHAR2", label: "NVARCHAR2" },
];

function quoteId(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

export const oracleLikeTableDesignerDriver: TableDesignerDriver = {
  ...createGenericDriver("oracle", "Oracle"),
  createEmptyField: () => createEmptyField("VARCHAR2"),
  getTypeOptions: () => ORACLE_TYPES,
  fromSchema: fromSchemaGeneric,
  validate: validateGeneric,
  buildPreviewSql(model, dbName) {
    const schema = dbName.trim();
    const tableRef = schema
      ? `${quoteId(schema)}.${quoteId(model.tableName)}`
      : quoteId(model.tableName);
    const lines = model.fields.map((field) => {
      const type =
        field.length.trim() && /varchar2|nvarchar2|char|number|raw/i.test(field.type)
          ? `${field.type}(${field.length.trim()})`
          : field.type;
      const parts = [`  ${quoteId(field.name)} ${type}`];
      if (field.isPk) parts.push("PRIMARY KEY");
      if (!field.nullable) parts.push("NOT NULL");
      if (field.isAutoIncrement) parts.push("GENERATED BY DEFAULT AS IDENTITY");
      if (field.defaultValue.trim()) parts.push(`DEFAULT ${field.defaultValue.trim()}`);
      return parts.join(" ");
    });
    for (const index of model.indexes) {
      if (index.primary || index.columns.length === 0) continue;
      const cols = index.columns.map((c) => quoteId(c)).join(", ");
      const kind = index.unique ? "UNIQUE INDEX" : "INDEX";
      lines.push(`  ${kind} ${quoteId(index.name || "idx_" + index.columns.join("_"))} (${cols})`);
    }
    return [
      `-- ${dbName}.${model.tableName}`,
      model.comment.trim() ? `-- ${model.comment.trim()}` : "",
      `CREATE TABLE ${tableRef} (`,
      lines.join(",\n"),
      ");",
    ]
      .filter(Boolean)
      .join("\n");
  },
  buildApplySql: buildApplySqlOracle,
  createEmptyIndex,
};
