[package]
name = "omnipanel-plugin-pkg"
version.workspace = true
edition.workspace = true
license.workspace = true
description = ".omni-plugin 包格式：打包、规范化字节流、ed25519 验签"

[dependencies]
omnipanel-plugin = { path = "../omnipanel-plugin" }
semver = "1"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zip = { version = "2", default-features = false, features = ["deflate"] }
flate2 = "1.1.9"
tar = "0.4.46"
ed25519-dalek = { version = "2", features = ["rand_core"] }
hex = "0.4"
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"
