import re
from pathlib import Path

ipc = Path("crates/omnipanel-server/src/ipc.rs").read_text(encoding="utf-8")
cmds = set(re.findall(r'"([a-z0-9_]+)"\s*=>', ipc))
plans = {
    "P1": """set_terminal_tmux_mode invalidate_tmux_cache ssh_tmux_attach_session ssh_tmux_capture_pane ssh_tmux_kill_session ssh_tmux_list_sessions ssh_tmux_list_windows ssh_tmux_tab_stats ssh_terminal_info ssh_terminal_set_direct_mode ssh_connect ssh_connect_config_host ssh_list_config_hosts ssh_generate_key ssh_import_key ssh_delete_key ssh_read_key_private ssh_read_key_public sftp_log_open sftp_log_read_lines sftp_log_tail_initial sftp_log_tail_start sftp_log_tail_stop local_log_open local_log_read_lines local_log_tail_initial local_log_tail_start local_log_tail_stop sftp_cache_for_preview sftp_probe_media sftp_open_media_stream sftp_close_media_stream terminal_history_clear_all terminal_history_clear_session terminal_history_counts terminal_history_load_session terminal_history_remove_block terminal_history_upsert_blocks""".split(),
    "P2": """db_redis_client_kill db_redis_dbsize db_redis_delete_key db_redis_key_detail db_redis_search_keys db_redis_set_key db_redis_slowlog db_introspect_schema db_introspect_table db_get_table_details db_table_ddl db_batch_table_ddl db_create_database db_list_character_sets db_list_connection_users db_list_databases_with_stats db_list_table_details db_data_sync_generate_sql db_data_sync_read_sql_file db_data_sync_write_sql_file db_schema_sync_preview_sql db_sync_row_diff_page db_mysql_export_delete db_mysql_export_list db_mysql_export_save_as db_qdrant_delete_points""".split(),
    "P3": """file_save_connection file_test_connection file_local_temp_dir write_text_file file_index_build file_index_cancel file_index_clear file_index_search file_index_status file_index_storage_info file_transfer_cancel file_transfer_clear_finished file_transfer_enqueue file_transfer_list file_transfer_plan file_transfer_retry file_transfer_set_concurrency file_transfer_set_rate_limit""".split(),
    "P4": """docker_service_create docker_service_list docker_service_logs docker_service_remove docker_service_update docker_swarm_init docker_swarm_inspect docker_swarm_join docker_swarm_leave docker_node_inspect docker_node_list docker_node_remove docker_node_update docker_stack_deploy docker_stack_list docker_stack_remove docker_stack_services""".split(),
    "P5": """provider_registry_load provider_registry_save provider_list_models_cmd cli_provider_list_cmd cli_provider_patch_cmd cli_provider_remove_cmd cli_provider_upsert_cmd embedding_provider_get embedding_provider_sync web_search_get_config web_search_set_config skill_list skill_create skill_get skill_update skill_remove skill_set_enabled agent_prompt_list agent_prompt_reset agent_prompt_save builtin_tool_audit_list builtin_tool_set_enabled ai_list_backends""".split(),
    "P6": """knowledge_list knowledge_list_chunks knowledge_list_revisions knowledge_save knowledge_save_asset knowledge_delete knowledge_delete_chunks knowledge_search knowledge_tags knowledge_increment_usage knowledge_restore_revision knowledge_asset_path knowledge_todo_delete knowledge_todo_list knowledge_todo_save tag_list_tree tag_list_used_by tag_create tag_rename tag_move tag_delete tag_set_color tag_query_resources tag_suggest resource_set_tags resource_add_tag resource_remove_tag resource_list_knowledge resource_list_profiles resource_list_tags resource_get_profile resource_find_similar resource_delete_observations resource_save_observation search_everywhere todo_list_delete todo_list_list todo_list_save todo_task_delete todo_task_list todo_task_save todo_step_delete todo_step_save""".split(),
    "P7": """workflow_list workflow_get workflow_save workflow_delete workflow_run workflow_stop workflow_executions workflow_get_execution task_list task_get task_get_output task_save task_update_status task_delete task_run task_stop task_events_list bg_task_cancel bg_task_history_list bg_task_list""".split(),
    "P8": """secrets_vault_lock secrets_vault_unlock secrets_vault_status secrets_vault_pull secrets_vault_push third_party_account_delete third_party_account_list third_party_account_upsert audit_log_append audit_log_recent execute_action""".split(),
}
for k, v in plans.items():
    miss = [c for c in v if c not in cmds]
    print(f"{k}: {len(v)-len(miss)}/{len(v)} ok; missing={miss}")
print("total registered", len(cmds))
